{{ if .Values.staging.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
    nginx.org/client-max-body-size: "10m"
    nginx.org/location-snippets: |
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection "Upgrade";
  name: staging-{{ .Release.Name }}
  labels:
    app.kubernetes.io/project: bo
    app.kubernetes.io/component: ingress
    app.kubernetes.io/name: staging-{{ .Release.Name }}
    app.kubernetes.io/brand: cardona
    app.kubernetes.io/part-of: cardona
    app.kubernetes.io/env: staging
spec:
  ingressClassName: {{ .Values.ingress.controller.name | quote }}
  tls:
    - hosts:
        - {{ include "ingressStagingHostname" . }}
      secretName: {{ include "ingressStagingHostname" . }}
  rules:
    - host: {{ include "ingressStagingHostname" . }}
      http:
        paths:
          - path: /auth
            pathType: Prefix
            backend:
              service:
                name: staging-{{ .Release.Name }}
                port:
                  name: http
{{- if .Values.staging.cardonaPanelSercive }}
          - path: /cardona
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.staging.cardonaPanelSercive }}
                port:
                  name: http
{{- end }}
{{- if .Values.staging.alaroPanelSercive }}
          - path: /alaro
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.staging.alaroPanelSercive }}
                port:
                  name: http
{{- end }}
{{- if .Values.staging.marbellaPanelSercive }}
          - path: /marbella
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.staging.marbellaPanelSercive }}
                port:
                  name: http
{{- end }}
{{- end }}
