{{ if .Values.staging.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: staging-{{ .Release.Name }}
  labels:
    app: staging-{{ .Release.Name }}
spec:
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: staging-{{ .Release.Name }}
{{- end }}